export const Routes = {
  Splash: 'Splash',
  PinLogin: 'PinLogin',
  Dashboard: 'Dashboard',
  KamaiEntry: 'KamaiEntry',
  KharchEntry: 'KharchEntry',
  MachineEntry: 'MachineEntry',
  CustomerList: 'CustomerList',
  AddCustomer: 'AddCustomer',
  EditCustomer: 'EditCustomer',
  DateReport: 'DateReport',
  MonthlyReport: 'MonthlyReport',
  MachineReport: 'MachineReport',
  Settings: 'Settings',
} as const;
